//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GulkortetNETFramework.Models;

namespace GulkortetNETFramework.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;


    public partial class CardContext : DbContext
    {
        public CardContext()
            : base("name=CardContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kort> Kort { get; set; }
    }
}
